# GitHub Pages configuration - FORCE GITHUB PAGES DEFAULT DOMAIN ONLY
# Explicitly disable ALL custom domains and force GitHub Pages default
domain: proto-sdk.github.io
url: https://proto-sdk.github.io
baseurl: /proto-api-docs

# Disable Jekyll processing since we have static files
plugins: []

# Force GitHub Pages settings
enforce_ssl: true
github: [metadata]

# Explicitly prevent custom domain usage
custom_domain: false
